<div class="subpage-card">

    <div class="subpage-header">

        <h1 class="subpage-title">
            View Detailed System Reports
        </h1>

    </div>

    <table class="report-table">

        <thead>
            <tr>
                <th>Report Name</th>
                <th>Category</th>
                <th>Date Range</th>
                <th>Generated By</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>

            <tr>
                <td>
                    <strong>Q3 Financial Audit & Revenue</strong>
                </td>

                <td>
                    Financial
                </td>

                <td>
                    Jul 2026 - Sep 2026
                </td>

                <td>
                    Sarah Jenkins
                </td>

                <td>
                    <a href="#"
                       style="color:#006f6a; font-weight:600; text-decoration:none;">
                        View & Download PDF
                    </a>
                </td>
            </tr>

            <tr>
                <td>
                    <strong>Annual Veterinary Clinical Outcomes</strong>
                </td>

                <td>
                    Medical
                </td>

                <td>
                    Jan 2026 - Sep 2026
                </td>

                <td>
                    Dr. Michael Vance
                </td>

                <td>
                    <a href="#"
                       style="color:#006f6a; font-weight:600; text-decoration:none;">
                        View & Download PDF
                    </a>
                </td>
            </tr>

            <tr>
                <td>
                    <strong>Staff Productivity & Consultation Log</strong>
                </td>

                <td>
                    Operations
                </td>

                <td>
                    Aug 2026 - Sep 2026
                </td>

                <td>
                    Sophia Martinez
                </td>

                <td>
                    <a href="#"
                       style="color:#006f6a; font-weight:600; text-decoration:none;">
                        View & Download PDF
                    </a>
                </td>
            </tr>

        </tbody>

    </table>

</div>